/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wg_core_Kernel */

#ifndef _Included_org_wg_core_Kernel
#define _Included_org_wg_core_Kernel
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_org_wg_core_Kernel_readMemoryInt
  (JNIEnv * env, jclass jc, jint pid, jint address);

JNIEXPORT jboolean JNICALL Java_org_wg_core_Kernel_zoulu
	(JNIEnv * env, jclass jc, jint pid, jint x,jint y);

JNIEXPORT jboolean JNICALL Java_org_wg_core_Kernel_sendPack
  (JNIEnv * env, jclass jc, jint pid, jbyteArray bs);

JNIEXPORT jfloat JNICALL Java_org_wg_core_Kernel_readMemoryFloat
	(JNIEnv * env, jclass jc, jint pid, jint address);

JNIEXPORT jstring JNICALL Java_org_wg_core_Kernel_readMemoryStr
  (JNIEnv * env, jclass jc, jint pid, jint address);

JNIEXPORT jboolean JNICALL Java_org_wg_core_Kernel_swhc
  (JNIEnv * env, jclass jc, jint pid);

JNIEXPORT jboolean JNICALL Java_org_wg_core_Kernel_xinpan
  (JNIEnv * env, jclass jc, jint pid, jint bag, jint num);

JNIEXPORT jboolean JNICALL Java_org_wg_core_Kernel_jhnpc
  (JNIEnv * env, jclass jc, jint pid, jint uid);

JNIEXPORT jboolean JNICALL Java_org_wg_core_Kernel_jrw
	(JNIEnv * env, jclass jc, jint pid, jint uid);

JNIEXPORT jboolean JNICALL Java_org_wg_core_Kernel_lua
  (JNIEnv * evn, jclass jc, jint pid, jstring js);

JNIEXPORT jboolean JNICALL Java_org_wg_core_Kernel_trhy
	(JNIEnv * env, jclass jc, jint pid, jint uid);

JNIEXPORT jboolean JNICALL Java_org_wg_core_Kernel_closeNpc
	(JNIEnv * env, jclass jc,int pid);
#ifdef __cplusplus
}
#endif
#endif
